### ISSUE TITLE
Unable to get event

### ISSUE THREAD

**Issue by goranprijic** [SocketMobile/scanapi-cordova#2]
Hi

I was following the instructions for implementation but I couldn't get it work. `SocketScanApi` object does exist, `useScanApi` method also, but I don't get any events on scan.

I noticed this error in xdebug:

```
2017-12-27 10:09:21.479174 POS[283:116969] CDVPlugin class ScanApiCordova (pluginName: ScanApiCordova) does not exist.
2017-12-27 10:09:21.479274 POS[283:116969] ERROR: Plugin 'ScanApiCordova' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2017-12-27 10:09:21.479370 POS[283:116969] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["ScanApiCordova1342759654","ScanApiCordova","useScanApi",[""]]
```

I used this SDK https://monosnap.com/file/dpBGlrvVxYCV0jQpvMJnUl62Ay1ZjR and everything went ok (without errors).

I have this in config.xml:

```
<plugin name="com-socketmobile-scanapi-cordova" spec="../scanapi-cordova" />
```

So, `scanapi-cordova` is located in the same folder like project. I run `cordova plugin add ../scanapi-cordova` to add cordova plugin, and that also went ok.

Can someone point what I am doing wrong? Thanks in advance

**Comment by EricGlaenzer** [comment]
Do you have a copy of the Socket ScanAPI SDK installed on your machine? This Cordova plugin does require the ScanAPI SDK.

**Comment by goranprijic** [comment]
Yes, I have this one https://monosnap.com/file/dpBGlrvVxYCV0jQpvMJnUl62Ay1ZjR

**Comment by EricGlaenzer** [comment]
Can you check if your iOS project settings Supported External Accessory has the protocol string set correctly? It should have an entry like: `com.socketmobile.chs`.
I would also make sure the scanner is configured in App Mode for MFi. (By default the scanner is configured in Basic mode) which makes the scanner similar to a keyboard (HID).

**Comment by EricGlaenzer** [comment]
We actually have a more recent version of ScanAPI SDK available on our website: version 10.3.93. Can you give it a try with this version?

**Comment by goranprijic** [comment]
OK, thanks. I will try that and I will get back with more info.

**Comment by goranprijic** [comment]
Hi Eric. Where should I look for version 10.3.93? I only get 10.3.90

**Comment by EricGlaenzer** [comment]
This version should appear in the readme.txt. I downloaded myself yesterday from Socket website so I am fairly certain that's correct. I also created quickly an app by using `cordova create`, and by following the instructions in the readme of this github project to make sure they are still correct, and tested everything on iOS 11.2.

**Comment by goranprijic** [comment]
From this page https://www.socketmobile.com/developers/developer-login-new/portal/downloads ? It shows 10.3.90 in readme now... And it seems that the last update was in 2016

**Comment by EricGlaenzer** [comment]
Apparently there is something weird about the cache of your browser. Can you clear your browser cache, log out and log back in? That should show the latest download link.

**Comment by goranprijic** [comment]
Yes, it's different URL, there seems to be two download pages. Will try now with the new version

**Comment by goranprijic** [comment]
Now `cordova build ios` throws `Error code 65 for command: xcodebuild with args...` . Build is working without adding this plugin. I'm using Xcode 9.1

**Comment by EricGlaenzer** [comment]
not sure what's happening here. I am using Xcode 9.2, and I am practically sure I tried with an earlier version when developing this plug-in, and I updated cordova to version 8.0.0. I would recommend first to try on a simple app first.

**Comment by cnormand127** [comment]
Eric, I'm working with Goran. Is the plugin supposed to work with all your scanner? we use 7Ci, 7 Qi and 800. Also will it work only in Mfi mode? We tried with a 7Ci in Mfi and didn't trigger the event in the app. Thanks

**Comment by EricGlaenzer** [comment]
Yes it works with all the Socket Scanners and they all support MFi mode. Did you try with just a plain default cordova app? You can have this up and running in no time by copy paste the code in the Readme and see the events fired as expected. At least this will give you the confirmation that the scanner is connected in the right mode and the cordova app can see the events.

**Comment by EricGlaenzer** [comment]
@goranprijic @cnormand127 : I would like to know if you have your solution working and if there is anything else I can help with. Thanks!

**Comment by goranprijic** [comment]
We haven't had time to deal with this since, but we will probably continue next week with creating blank cordova project as you suggested. Thanks

**Comment by goranprijic** [comment]
I tried building the blank cordova project today. On one Mac (cordova 8.0, ios platform 4.5.4, xcode 9.0.1, hight siera 10.13) I successfully created and built the project. But I can't build on another Mac (cordova 8.0, ios platform 4.5.4, xcode 9.1, hight siera 10.13.2). I get this error when running build:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I remove the plugin, then the project is successfully built so it seems that the problem is caused by plugin.

I assume that everything will work if I update xcode to 9.2 (as you suggested). But my concern is adding such a package to the project if it doesn't support various stacks.

**Comment by EricGlaenzer** [comment]
@goranprijic Did you install the ScanAPI SDK on that new Mac and follow the instructions? The libScanApiCore.a library file contains all the processors. If you go to `<your project>/plugins/com-socketmobile-scanapi-cordova/src/ios/sdk/lib/` you should see the libScanApiCore.a file to which you can inspect its architecture supported by doing a `lipo -detailed_info libScanApiCore.a`. The x86_64 architecture should be listed there.

**Comment by goranprijic** [comment]
Yes, x86_64 is listed there. But the error still occur...

**Comment by EricGlaenzer** [comment]
I think to speed up things we should schedule a call. Can you send us an email at developers@socketmobile.com with your contact information? That way we can schedule a call today or Monday.

**Comment by goranprijic** [comment]
I upgraded Xcode to 9.2, now it looks ok. But still, I have concern about support of this package regarding various stacks, for example if I upgrade cordova, os, xcode or anything else in the future...

**Comment by EricGlaenzer** [comment]
This Cordova plugin of our ScanAPI SDK is really simple. The main component is the SDK that we provide for ObjectiveC and Swift. We continue to support this SDK. The rest of the plugin is mostly code you can see, modify and submit pull request if necessary. This code is really a very simple wrapper around our SDK. Although we are in the process of releasing a new version of our SDK called Capture, for which we will release in the near future a Cordova plugin that will expose more of the SDK functionalities than the current Cordova plugin for ScanAPI. Until the new Capture plugin is released we will continue to support this ScanAPI plugin.
